# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 027b66858e3597aae38ce0be53d13421c7038cc309d2ebeee267a3401344af346c3d9f52b1a516074f8712b78fa4ebb2f9f536b75afd6968afc38dc1b5c9e222

test:
  secret_key_base: 337a8a6d6aedb9dfefe465332a09770c533476033d8ee100b1764830a506ea2dbebb5a73d3da0542a9fdeb969717eb6b00bafc5e17fa491e4a6c812bf9040834

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
